### ISSUE TITLE
Performance considerations

### ISSUE THREAD

**Issue by Elufimov** [haproxytech/haproxy-spoa-dotnet#1]
Hi! How bad would be performance penalty without spop async feature and on what rpm/concurrent sessions aims this spoa implementation?

**Comment by NickMRamirez** [comment]
Hi @Elufimov This is something good to test. Or, if you can determine a baseline requirement, see if this library meets your needs? What requests per second is needed?

I would suggest comparing it to the [Go implementation](https://github.com/criteo/haproxy-spoe-go), which allows async, but programming with different languages would introduce its own variables into the test and possibly not be an apples-to-apples comparison.

**Comment by NickMRamirez** [comment]
Closing this for now, but please reopen it if the discussion should be renewed.
