### ISSUE TITLE
API proposal: async version of IFrameProcessor.HandleStream

### ISSUE THREAD

**Issue by lkstz** [haproxytech/haproxy-spoa-dotnet#9]
I'd like to do some async logic inside of `IFrameProcessor.HandleStream` `notifyHandler` callback.
Currently, this requires some dirty hacks because there is no version of `HandleStream` that accepts a `Task<IList<SpoeAction>>` as return value.

I'd therefore like to propose the addition of the following API to `IFrameProcessor`:

```csharp
/// <summary>
/// Handles receiving and sending frames on the given stream.
/// </summary>
/// <param name="stream">The stream to receive and send frames on</param>
/// <param name="notifyHandler">Function to invoke when a NOTIFY frame is received</param>
Task HandleStreamAsync(Stream stream, Func<NotifyFrame, Task<IList<SpoeAction>>> notifyHandler);
```

Ideally, we could use `ValueTask` and `ValueTask<T>` instead of `Task` and `Task<T>`, however, as this library targets .NET Standard 2.0, `ValueTask` and `ValueTask<T>` are not available. As a possible workaround, this package could depend on `System.Threading.Tasks.Extensions`, which provides `ValueTask` and `ValueTask<T>` for .NET Standard 2.0.

Implementing the method in `FrameProcessor` could be done in several ways, the most basic one would be to copy the current `HandleStream` method, adjust its signature, make it async and await the two calls to `notifyHandler`.

Please let me know if this something you'd consider adding to the API, if so, I'd be happy to provide a PR implementing the changes described above.

**Comment by NickMRamirez** [comment]
Should we upgrade to a newer .NET implementation like .NET 5.0? I'm not against changing the target framework, and since I spend less time in the .NET world these days, I'm open to your suggestions. From what I am reading, there won't be any new .NET Standard releases after 2.1. It looks like most Linux distros have support for .NET 5.0.

Async support seems like it would be a good addition to this library.

**Comment by lkstz** [comment]
Upgrading to .NET 5.0 would be an option, I'd recommend multi-targetting the library so that at least one LTS version of .NET (currently Core 3.1) is supported. One possible downside would be the drop of .NET Framework support.

**Comment by NickMRamirez** [comment]
@kolletzki Thanks for the suggestion! I will look into multi-targeting. If you would like to open a pull request, you are welcome to. I will try to review it ASAP.
